### PR TITLE
change IsInside check for UnionAll to act only on the selected solid not the full collection.

### LINKED ISSUE #209: Possible bug in sampling from multiple sources
It seems that when we try to sample from multiple sources we do not get the correct fraction of vertices in each physical volume (according to their volume).

> **Summary**: After alot of checks I find this is due (atleast partially) to the way the `IsInside` check acts on the full list of volumes and bounding boxs can overlap.

I simulated events (100 keV beta's) in the Germanium detectors for L-200 (i.e. using the following macro).
```
/control/execute cfg/detectors.mac
/RMG/Output/NtuplePerDetector false
/run/initialize

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume B.*
/RMG/Generator/Confinement/Physical/AddVolume C.*
/RMG/Generator/Confinement/Physical/AddVolume P.*
/RMG/Generator/Confinement/Physical/AddVolume V.*

/RMG/Generator/Select GPS
/gps/particle e-
/gps/energy 100 keV

/run/beamOn 1000000
```
I then plotted the fraction of vertices in each detector (making use of `legendhpges.is_inside` for the check). I also plotted the fraction of hits (taking the first uid in the hit as the channel). I compare this to the expectation according to the detector volume.

```python
from lgdo import lh5
from matplotlib import pyplot as plt
import awkward as ak
import numpy as np
from tqdm import tqdm
import legendhpges as hpges
import pyg4ometry as pg4
from numpy import pi
from pygeomtools.detectors import get_sensvol_metadata
import copy

plt.rcParams["lines.linewidth"] = 1
plt.rcParams["font.size"] = 12


# get the detector info
reg = pg4.gdml.Reader("cfg/l200.gdml").getRegistry()
reg_tmp = pg4.geant4.Registry()
detectors = list(reg.physicalVolumeDict.keys())

detectors = [det for det in detectors if det[0] in ["V","P","B","C"]]

det_map = {det: {"uint":get_sensvol_metadata(reg,det)["daq"]["rawid"],
                 "pos":reg.physicalVolumeDict[det].position.eval(),
                 "hpge":hpges.make_hpge(get_sensvol_metadata(reg,det),registry=reg_tmp)} for idx,det in enumerate(detectors)}

# get vertices and add which detector it is in
# append with the uint and the local positions
vertices = lh5.read_as("stp/vertices","output/l200_beta.lh5","ak")

uint = np.array(np.full_like(vertices.time,-1),dtype=int)
xlocal = np.array(1000*vertices.xloc)
ylocal = np.array(1000*vertices.yloc)
zlocal = np.array(1000*vertices.zloc)

positions = np.array(np.transpose(np.vstack([vertices.xloc*1000,vertices.yloc*1000,vertices.zloc*1000])))
for det in tqdm(det_map.keys()):
    if (det=="V02160A"):
        continue
        
    local_positions = copy.copy(positions)
    local_positions-=det_map[det]["pos"]

    is_inside = det_map[det]["hpge"].is_inside(local_positions)

    uint[is_inside]=det_map[det]["uint"]
    xlocal[is_inside]-=det_map[det]["pos"][0]
    ylocal[is_inside]-=det_map[det]["pos"][1]
    zlocal[is_inside]-=det_map[det]["pos"][2]

vertices["uid"]=uint
vertices["xlocal"]=xlocal
vertices["ylocal"]=ylocal
vertices["zlocal"]=zlocal

# get the uid per hit

steps = lh5.read_as("stp/germanium","output/l200_beta.lh5","ak")
steps = ak.unflatten(steps, ak.run_lengths(steps.evtid))
uid= ak.fill_none(ak.firsts(steps.det_uid,axis=-1),-1)
evtid = ak.fill_none(ak.firsts(steps.evtid,axis=-1),-1)
hits = ak.Array({"evtid":evtid,"uid":uid})

# plot the fraction of vertices in each channel
def make_plot(vert,hit):
    
    fraction_vert= []
    fraction_vert_err = []
    fraction_hit = []
    expected_fraction = []
    names = []

    n_tot = len(vert)
    vol_tot = 0 

    for det in det_map.keys():
        vol_tot +=float(det_map[det]["hpge"].volume.magnitude)

        if (det=="V02160A"):
            continue
        n_sel_vert  = len(vert[vert.uid==det_map[det]["uint"]])
        n_sel_hit   = len(hit[hit.uid==det_map[det]["uint"]])
        
        names.append(det)
        fraction_vert.append(100*n_sel_vert/n_tot)
        fraction_vert_err.append(100*np.sqrt(n_sel_vert)/n_tot)
        fraction_hit.append(100*n_sel_hit/n_tot)
        expected_fraction.append(float(det_map[det]["hpge"].volume.magnitude))

    expected_fraction = 100*np.array(expected_fraction)/vol_tot
    fraction_vert= np.array(fraction_vert)
    fig, ax = plt.subplots(figsize=(16,4))

    ax.errorbar(np.arange(len(names)),fraction_vert,yerr=fraction_vert_err,fmt=".",label="Vertices")
    ax.errorbar(np.arange(len(names))-0.1,fraction_hit,fmt="x",label="Hits")

    ax.errorbar(np.arange(len(names)),expected_fraction,fmt=".",label="Expected")
    ax.set_xlabel("Channel Index")
    ax.set_ylabel("Fraction of vertices [%]")
    ax.set_xticks(np.arange(len(names)),names,rotation=90,fontsize=10)
    ax.legend()
    ax.grid()
    plt.tight_layout()

make_plot(vertices,hits)
```

The result is quite large deviations from the expectation. However, the fraction of vertices matches quite closely the fraction of hits (suggesting I didn't make a mistake in my script). I checked the script and I do not see any obvious issue.
image
This appears both with and without multithreading...

To show a bit more closely I zoomed into some channels.
image
We see for some (usually large detectors) very large deviations, while others appear fairly compatible with the expectation.

We should check this carefully and understand the bug.. ideas:
- [x] check if the bug appears in the single-threaded mode (it does)
- [x] look at a simplified geometry (just few volumes),
- [x] check volume in `pyg4ometry` vs geant4
- [x] check the position of vertices especially for channels with large deviations
- [x] add some more debug information

### PR DESCRIPTION
**Pull request by tdixon97**
Fixes #209 (at least for UnionAll), however, maybe we would like a cleaner solution than making a container with only 1 solid in it.
We also need to:
- [ ] include the tests of #209 as unit tests
- [ ] check + fix + test Intersections and subtractions.

### CODE REVIEW

**Comment by gipert** [comment]
Yes please, can you implement `SampleableObject::IsInside()` and update `SampleableObjectCollection::IsInside()` to use it?

https://github.com/legend-exp/remage/blob/f229251aa205ce4d67c8cca7b727843f67f67cc9/src/RMGVertexConfinement.cc#L110-L120

**Comment by tdixon97** [comment]
Yeah I thought about it, I can definitely do this if we prefer that solution.

**Comment by gipert** [comment]
I want to setup Python for tests today, with an example, after #210 is merged.

**Comment by tdixon97** [comment]
Ok lets try to implement the tests later then, I have anyway all the python scripts I used.

**Comment by tdixon97** [comment]
Have a look now @gipert

**Comment by gipert** [comment]
Can you also update `SampleableObjectCollection::IsInside()` to use it?

**Comment by tdixon97** [comment]
Yes sure, I can do it later.
________________________________

**Comment by gipert** [comment]
Did it no worries, I merge this and you can add/fix the rest in a future PR.

**Pull request merged**
