### PR TITLE
Add option to reset global time after initial decay

### PR DESCRIPTION
**Pull request by ManuelHu**
see #135

### CODE REVIEW

**Comment by ManuelHu** [comment]
@tdixon97 I also added a warning for large global times after ~285 years of simulation time. This corresponds to 1 us time resolution.

```c++
std::cout << std::nextafter(285 * CLHEP::year, INFINITY) - 285 * CLHEP::year) / CLHEP::us << std::endl;
// -> 1.024
```

the warning is only shown once per thread to avoid it being shown for each event.

**Comment by tdixon97** [comment]
I think the warning is good but then I wonder if we want the limit by default to be set to this?

**Comment by ManuelHu** [comment]
that would give us non-deterministic, inconsistent and for users even more confusing behaviour: the limit does affect the true (sampled) lifetime, and not the half-life. So some decays would go through, and some not.
also it applies to the time of the individual decays,  and not the (summed) global time in the event. So 3 decays with 100 years lifetime would not trigger the threshold, but only this warning.

Also I would suppose that - when I want to simulate some specific decay - remage should also just do how it is instructed.

**Comment by tdixon97** [comment]
Hmm I am still not sure, I think `remage` should perform some sanity checks and make the user force it to do something that would give a nonsense output. What do you think @gipert ? Maybe the check should be on the half-lives not on the sampled half-lives as you say

**Comment by gipert** [comment]
I think the check should be on half-lives, not the sampled decay times. Will anyone really want to cut on the sampled times?

**Comment by tdixon97** [comment]
I agree, cutting on sampled times is not a nice behaviour really

**Comment by ManuelHu** [comment]
probably not. This is why this PR is raising that builtin limit acting on sampled lifetimes. But we cannot really disable this functionality. (also because the API to set the limit from C++ only exists in 11.2+, and not in 11.0-11.1).

But this is a more complex issue, as Toby wants to enforce a maximum time uncertainty in output.
This cannot achieved by cutting on individual decay half-lifes. It would have to be a **check on the sum of all half-lives in a decay chain**. But this information is not readily available in Geant4, so we would need to track it on our own.

Such a check would give us reproducability, but would not really solve the output timing issue? If a chain approaches this 285yr region, a lot of events would still have time uncertainty > 1us _even after that cut_...
Example: Ar39 has 268yr half-life...

---

or we just want an option to constrain half-lifes of daughter nuclei (not summed); we already have this option. I think that having options for primaries do not make sense at all - if a user requests a specific isotope, they should already know best that they really want it...

**Pull request merged**
